### PR TITLE
scaled some components

### PR DESCRIPTION
**Pull request by t-ch3n-dotcom**
couldn't figure out how to scale polaroid photo to mobile

### CODE REVIEW

**Comment by Elias2660** [comment]
I like what you've done for the top two panels! Could you explain the polaroid photo part?

@connor132435 could you tell us progress on your end of the work plz?

**Review by Elias2660 — APPROVED** [review]
It's okay except it doesn't totally fix the problem.

**Comment by Elias2660** [comment]
@willpill give comments plz

**Comment by willpill** [comment]
Will review tomorrow

**Pull request merged**
